### ISSUE TITLE
websocket.client returns undefined

### ISSUE THREAD

**Issue by yeliex** [yodaos-project/ShadowNode#542]
run `test/deps/websocket-server.js` 
throw exception
```js
TypeError: Expected a constructor.
    at undefined (/tmp/ShadowNode-master/test/deps/websocket-server.js:1:1)
    at undefined (module:211:36)
    at undefined (module:164:23)
    at undefined (module:234:26)
    at undefined (iotjs.js:2:2)
    at undefined (iotjs.js:1:1)
```

```js
console.log(require('websocket').client) // => function(){/* ecmascript */}
console.log(require('websocket').server) // => undefined
```

**Comment by yeliex** [comment]
all test success except `test_websocket_connection.js`

**Comment by yorkie** [comment]
Hi @yeliex ShadowNode supports the WebSocket client only, and we run `test/deps` in Node.js usually, see https://github.com/yodaos-project/ShadowNode/blob/master/.travis.yml#L41-L44.

**Comment by yeliex** [comment]
@yorkie
